// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffcqigvovtntniwlukxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmY3FpZ3ZvdnRudG5pd2x1a3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDIwMjIsImV4cCI6MjA3MTc3ODAyMn0.3lCqkJ6k9Rz33r8ByFxGyzSFpkDH0JmGE1o6WvIBNs4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});